use() {
  rubyver=$1
  gemver=$2

  rvm use $rubyver
  rvm gemset create $(gemset)
  rvm gemset use $(gemset)
  rvm --force gemset empty $(gemset)
  rvm install rubygems $gemver
}

gemset() {
  echo "temp-$$"
}

build() {
  dir=$(dirname $1)
  gemspec=$(basename $1)
  (cd $dir; rm -f *.gem; gem build $gemspec)
}

clean() {
  rvm --force gemset delete $(gemset)
}

setup() {
  project=$1
  pushd fixtures
  if [ -f "${project}.sh" ] ; then
    sh "${project}.sh"
  else
    echo "No such project setup file: fixtures/${project}.sh"
    return 1
  fi
  popd
}

check() {
  project=$1
  user_rubyver=$2
  user_gemver=$3

  (
    [ ! -d log ] && mkdir log
    exec > log/$1.$2.$3.log
    exec 2> log/$1.$2.$3.err
    setup $project

    use 1.9.3 1.8.18
    build fixtures/$project/$project.gemspec
    clean

    # simulate Ubuntu 11.10's defaults
    use $user_rubyver $user_gemver

    # Test it
    #gem install --ignore-dependencies fixtures/$project/$project*.gem
    gem install fixtures/$project/*.gem
    rm fixtures/$project/$project*.gem
    ruby -rubygems -e "gem '$project'" 
    result=$?

    clean
    exit $result
  )
  result=$?

  testenv="ruby($(ruby -e 'puts RUBY_VERSION')) rubygems($(gem --version))"
  # Make sure it installed.
  if [ $result -ne 0 ] ; then
    echo "FAILURE - $project on $testenv"
  else
    echo "OK - $project on $testenv"
  fi
  echo "$result"
  return $result
}
